#!/usr/bin/env python3
"""Pre-commit hook to verify requirements.txt matches uv export output."""

import subprocess
import sys
import tempfile
from pathlib import Path


def main() -> int:
    # Get the project root (where pyproject.toml is)
    project_root = Path(__file__).parent.parent
    requirements_path = project_root / "requirements.txt"

    if not requirements_path.exists():
        print("ERROR: requirements.txt not found")
        return 1

    # Read current requirements.txt
    current_requirements = requirements_path.read_text()

    # Generate expected requirements with uv export (deterministic from lockfile)
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
        temp_path = f.name

    try:
        result = subprocess.run(
            ["uv", "export", "--no-dev", "--extra", "turso", "-o", temp_path],
            capture_output=True,
            text=True,
            cwd=project_root,
        )

        if result.returncode != 0:
            print(f"ERROR: uv export failed:\n{result.stderr}")
            return 1

        # Read generated requirements
        expected_requirements = Path(temp_path).read_text()

        # Compare (ignoring the comment line with the uv command since paths may differ)
        def normalize(content: str) -> list[str]:
            """Normalize requirements for comparison."""
            lines = []
            for line in content.strip().split("\n"):
                # Skip the autogenerated comment line (contains paths)
                if line.startswith("# This file was autogenerated"):
                    continue
                # Skip the uv command comment (contains paths)
                if line.strip().startswith("#    uv"):
                    continue
                lines.append(line)
            return lines

        current_lines = normalize(current_requirements)
        expected_lines = normalize(expected_requirements)

        if current_lines != expected_lines:
            print("ERROR: requirements.txt is out of sync with pyproject.toml/uv.lock")
            print("\nTo fix, run:")
            print("  uv export --no-dev --extra turso -o requirements.txt")
            print("\nDifferences found:")

            # Show what's different
            current_set = set(current_lines)
            expected_set = set(expected_lines)

            missing = expected_set - current_set
            extra = current_set - expected_set

            if missing:
                print("\nMissing from requirements.txt:")
                for line in sorted(missing)[:10]:  # Limit output
                    if line.strip():
                        print(f"  + {line[:80]}...")

            if extra:
                print("\nExtra in requirements.txt:")
                for line in sorted(extra)[:10]:  # Limit output
                    if line.strip():
                        print(f"  - {line[:80]}...")

            return 1

        print("requirements.txt is in sync with pyproject.toml/uv.lock")
        return 0

    finally:
        Path(temp_path).unlink(missing_ok=True)


if __name__ == "__main__":
    sys.exit(main())
