#!/usr/bin/env python3
"""Pre-commit hook to verify requirements.txt matches uv pip compile output."""

import subprocess
import sys
import tempfile
from pathlib import Path


def main() -> int:
    # Get the project root (where pyproject.toml is)
    project_root = Path(__file__).parent.parent
    requirements_path = project_root / "requirements.txt"

    if not requirements_path.exists():
        print("ERROR: requirements.txt not found")
        return 1

    # Read current requirements.txt
    current_requirements = requirements_path.read_text()

    # Generate expected requirements with uv
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
        temp_path = f.name

    try:
        result = subprocess.run(
            ["uv", "pip", "compile", "pyproject.toml", "--extra", "turso", "-o", temp_path],
            capture_output=True,
            text=True,
            cwd=project_root,
        )

        if result.returncode != 0:
            print(f"ERROR: uv pip compile failed:\n{result.stderr}")
            return 1

        # Read generated requirements and append -e .
        generated = Path(temp_path).read_text()
        expected_requirements = generated.rstrip() + "\n-e .\n"

        # Compare (ignoring the comment line with the uv command since paths may differ)
        def normalize(content: str) -> list[str]:
            """Normalize requirements for comparison."""
            lines = []
            for line in content.strip().split("\n"):
                # Skip the autogenerated comment line (contains paths)
                if line.startswith("# This file was autogenerated"):
                    continue
                # Skip the uv command comment (contains paths)
                if line.strip().startswith("#    uv pip compile"):
                    continue
                lines.append(line)
            return lines

        current_lines = normalize(current_requirements)
        expected_lines = normalize(expected_requirements)

        if current_lines != expected_lines:
            print("ERROR: requirements.txt is out of sync with pyproject.toml")
            print("\nTo fix, run:")
            print(
                "  uv pip compile pyproject.toml --extra turso -o requirements.txt && echo '-e .' >> requirements.txt"
            )
            print("\nDifferences found:")

            # Show what's different
            current_set = set(current_lines)
            expected_set = set(expected_lines)

            missing = expected_set - current_set
            extra = current_set - expected_set

            if missing:
                print("\nMissing from requirements.txt:")
                for line in sorted(missing):
                    if line.strip():
                        print(f"  + {line}")

            if extra:
                print("\nExtra in requirements.txt:")
                for line in sorted(extra):
                    if line.strip():
                        print(f"  - {line}")

            return 1

        print("requirements.txt is in sync with pyproject.toml")
        return 0

    finally:
        Path(temp_path).unlink(missing_ok=True)


if __name__ == "__main__":
    sys.exit(main())
